### PR TITLE
fixing some typos

### PR DESCRIPTION
**Pull request by fchapoton**
Just fixing some of the typos found using
`
sage --tox -e codespell -- darmonpoints/
`
and also some rst issues in the documentation found using
`
sage --tox -e rst -- darmonpoints/
`
Checklist
* [ ] Added an entry in `doc/news/`. 
* [ ] Added a test for this change.
* [ ] Updated the documentation.

### CODE REVIEW

**Comment by fchapoton** [comment]
ping ?

**Comment by fchapoton** [comment]
re-ping ?

**Comment by fchapoton** [comment]
nobody out there, it seems..

**Comment by mmasdeu** [comment]
I finally got around merging your pull request. Thank you @fchapoton for your work, and sorry for the silence...

**Pull request merged**
